version: '2'
services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=veryhardpassword
      - MYSQL_DATABASE=easyapp
      - MYSQL_USER=easyapp
      - MYSQL_PASSWORD=veryhardpassword

  application:
    image: easyappointments
    build:
      context: .
    volumes:
      - ./src:/app
    command: dev
    ports:
      - ${APP_HOST}:80:80
    environment:
      - DB_NAME=easyapp
      - DB_USERNAME=easyapp
      - DB_PASSWORD=veryhardpassword
      - DB_HOST=database:3306
      - APP_URL=localhost
    restart: always