version: '2'
services:
    database:
        image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
        - easyappointments-data:/var/lib/mysql
        restart: always

    application:
        image: easyappointments
        build:
            context: .
        ports:
        - 80:80
        environment:
        - DB_HOST=database:3306
        env_file:
        - .env
        volumes:
        - easyappointments-storage:/var/www/html/src/storage
        restart: always

volumes:
    easyappointments-data:
    easyappointments-storage:
