version: '2'
services:
    database:
        image: mysql:5.7
        environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

    application:
        image: easyappointments
        build:
            context: .
        volumes:
        - ../src:/var/www/html
        command: dev
        ports:
        - ${APP_HOST}:80:80
        environment:
        - DB_HOST=database:3306
        - APP_URL=localhost
        depends_on:
        - database
        env_file:
        - .env
        restart: always
