name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          php_extensions: gd
          version: 2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Test
        with:
          bootstrap: tests/bootstrap.php
          configuration: phpunit.xml
